server:
  port: 8888
spring:
  application:
    name: transcaction
  datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: mizhuo123
  url: jdbc:mysql://192.168.3.73:3306/demo
mybatis-plus:
  configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logstash:
  host: localhost
